### ISSUE TITLE
cloudfront_invalidate_root issue?

### ISSUE THREAD

**Issue by dlondero** [laurilehmijoki/s3_website#106]
Hi, I'm having troubles using `cloudfront_invalidate_root: true` because when pushing to s3 an invalidation for CloudFront is created (`Object Paths / /`, as expected I guess when changes are only in index.html) but when it's completed the index.html is not invalidated at all (can see an high Age in the response headers and no changes in html).

If I remove `cloudfront_invalidate_root: true` from `s3_website.yml` and push again this time I get `Object Paths / /index.html` and at the end the invalidation is correct (first having a miss from CloudFront and seeing changes in html).

Default root object in distribution settings looks ok (index.html).

What could I investigate further?

**Comment by dlondero** [comment]
@laurilehmijoki tested this finally with 2.7.5 and it works as expected invalidating `/index.html` correctly. Thanks!

**Comment by laurilehmijoki** [comment]
Thank you for the feedback!
