### ISSUE TITLE
Content type incorrectly detected

### ISSUE THREAD

**Issue by yanokwa** [laurilehmijoki/s3_website#119]
s3_website v2.3.1 uploads file.html listed at https://gist.github.com/yanokwa/76225701c6b9fde31ae9 as application/xhtml+xml even though the Content-Type is HTML. 

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://gmpg.org/xfn/11">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
```

Could we have a switch to use the extension of the file to determine content-type?

**Comment by johnlauck** [comment]
Just in case this is puzzling anyone, it sounds similar to https://github.com/laurilehmijoki/s3_website/issues/128
