### ISSUE TITLE
Add support for eu-central-1

### ISSUE THREAD

**Issue by laurilehmijoki** [laurilehmijoki/s3_website#126]
Tasks

* Add the endpoint **eu-central-1** into [s3_website](https://github.com/laurilehmijoki/s3_website/blob/1bd3feb4847509a8d35f6519cd575642d82fbf74/src/main/scala/s3/website/model/S3Endpoint.scala)
* Add the endpoint **eu-central-1** into [configure-s3-website](https://github.com/laurilehmijoki/configure-s3-website/blob/master/lib/configure-s3-website/s3_client.rb#L145)
* Update to AWS Signature version 4 in https://github.com/laurilehmijoki/configure-s3-website/blob/master/lib/configure-s3-website/http_helper.rb#L35

**Comment by schickling** [comment]
+1

**Comment by mobidev111** [comment]
Any news on this?

**Comment by laurilehmijoki** [comment]
Nope.

**Comment by mtsachev** [comment]
+1

Do you plan to add SIGV4 support soon?

**Comment by laurilehmijoki** [comment]
We should add the SIGV4 support as soon as possible. 

Can someone help on that? Pull requests are appreciated!

The SIGV4 needs to be added to https://github.com/laurilehmijoki/configure-s3-website/blob/master/lib/configure-s3-website/http_helper.rb#L35.

**Comment by schmitch** [comment]
+1 I need that aswell

**Comment by marcobehler** [comment]
+1

**Comment by kristofvanlandschoot** [comment]
+1

**Comment by sandys** [comment]
is there any plans for this moving forward ? most of the new regions are v4 only... and it is a matter of time before old regions are also moved to v4 only.

**Comment by laurilehmijoki** [comment]
Work-in-progress is here: https://github.com/laurilehmijoki/configure-s3-website/commits/aws-sign-v4 – I couldn't yet get the signing to work, I'm seeing the `The request signature we calculated does not match the signature you provided. Check your key and signing method.` error. Should probably debug with the help of <http://docs.aws.amazon.com/general/latest/gr/signature-v4-test-suite.html>.

I probably don't have time to finish this, so if this is important to you, feel free to pick up the work from the branch.

**Comment by laurilehmijoki** [comment]
As of version **2.15.1**, the following AWS Regions are supported (in addition to the other Regions):

* ap-northeast-2
* ap-south-1
* eu-central-1

For those who are interested in the implementation details, here are the changes that made this possible:

* <https://github.com/laurilehmijoki/s3_website/commit/58bf10472ab2e1fae6daa372117d78e9bb9db2d8>
* <https://github.com/laurilehmijoki/configure-s3-website/compare/b31bcde12fe66986322bd9e3cd9974476d6a78a6...93c7f328025a9c0b082222aa0e2a6cb34b958333>
