### ISSUE TITLE
Invalidation Issues

### ISSUE THREAD

**Issue by ericmillsio** [laurilehmijoki/s3_website#127]
When I deploy with s3_website, it invalidates the stylesheets. The issue with this is if you invalidate stylesheets at the same time as the html pages, you have a sort of race condition that causes the site's style to break for a lengthy period of time until the html pages are fully invalidated. They reference the old versioned styles, but they may no longer exist at the node you receive content from.

I'm not quite sure how to handle this. I could move the html pages to only serve straight from the s3 bucket (so they will never be an old copy), or keep around old version of stylesheets for at least 24 hours (not sure how best to do this). You guys have any thoughts or better ideas on this? Any help is appreciated. 

_note_ - config file has `cloudfront_invalidate_root: true`

**Comment by ioRekz** [comment]
Hello, I'm struggling with this one as well. Right now, I'm only depending on s3 website to push my website and that's perfect so I want to avoid adding other build step. Does anyone have an idea on how to version file on every push ?
