### ISSUE TITLE
Entity errors when pushing to s3

### ISSUE THREAD

**Issue by nealrs** [laurilehmijoki/s3_website#128]
Hiyo. I can successfully push my jekyll blog files to s3 & I'm _not_ using Cloudfront or gzip, but instead of rendering them correctly, I keep getting this entity error:

![screen shot 2014-10-30 at 8 56 05 pm](https://cloud.githubusercontent.com/assets/1568188/4854781/032b0cd6-6099-11e4-97f7-5a81c921f631.png)

even though the source looks good & renders well locally: 

![screen shot 2014-10-30 at 8 56 14 pm](https://cloud.githubusercontent.com/assets/1568188/4854783/09ff0418-6099-11e4-8a4c-3d7ac2db26de.png)

However, if I use transmit to upload the site, everything renders correctly:

![screen shot 2014-10-30 at 9 00 40 pm](https://cloud.githubusercontent.com/assets/1568188/4854797/5e8c2aec-6099-11e4-967f-0b38c2f968d2.png)

I think the gem works just fine -- but do I need to add something to my config? Thanks!

**Comment by johnlauck** [comment]
Just note here, using Poole/Hyde templates @nealrs comment was correct.  The fix is to remove `xmlns` and `xml:lang` from `<html>`  tag.  A default layout can use: 

 ```
<!DOCTYPE html>
<html lang="en-us">
```

**Comment by kissmygritts** [comment]
@johnlauck solution also necessary for Poole/Lanyon
