### ISSUE TITLE
.env not being picked up

### ISSUE THREAD

**Issue by dominiclovell** [laurilehmijoki/s3_website#139]
I have created a `.env` in the root directory.

The structure of the file:

```
AWS_ACCESS_KEY_ID=MY_ACCESS_KEY
AWS_SECRET_ACCESS_KEY=MY_SECRET
S3_BUCKET_NAME=my_bucket_name
```

However, when I try to push I continually receive the following error:

```
$ s3_website push --dry-run
[info] Simulating the deployment of /Users/Dom/my_site/_site/* to my_bucket
[fail] Failed to fetch an object listing (The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: B4F271DAF53A88C9))
[info] Summary: 2 operations failed.
[fail] Failed to push the website to http://my_bucket.s3-website-us-east-1.amazonaws.com
```

Note, I have removed the real values from the output above. 

If I hardcode the real values in the `s3_website.yml` everything works fine.

**Comment by laurilehmijoki** [comment]
Closing the issue, since it has been inactive for a long period of time. Please re-open if needed.
