### ISSUE TITLE
Win 8.1 SSL error on push

### ISSUE THREAD

**Issue by rdyar** [laurilehmijoki/s3_website#142]
I upgraded to the latest s3_website and now get the message below when I push
```
PS J:\AeroFS\Software\111-Hg-Repository\ePhotoPros> s3_website push
[info] The jar file is corrupted. (Expected checksum 4e379aae6d75790acc76afed21f335cb but got d41d8cd98f00b204e9800998ec
f8427e.)
[info] Downloading https://github.com/laurilehmijoki/s3_website/releases/download/v2.7.2/s3_website.jar into C:/Portable
Jekyll/ruby/lib/ruby/gems/2.0.0/gems/s3_website-2.7.2/s3_website-2.7.2.jar
C:/PortableJekyll/ruby/lib/ruby/2.0.0/net/http.rb:918:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read serv
er certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/net/http.rb:918:in `connect'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/net/http.rb:851:in `start'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/open-uri.rb:708:in `buffer_open'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/open-uri.rb:688:in `open'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/open-uri.rb:34:in `open'
        from C:/PortableJekyll/ruby/lib/ruby/gems/2.0.0/gems/s3_website-2.7.2/bin/s3_website:238:in `block in download_j
ar'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/open-uri.rb:36:in `open'
        from C:/PortableJekyll/ruby/lib/ruby/2.0.0/open-uri.rb:36:in `open'
        from C:/PortableJekyll/ruby/lib/ruby/gems/2.0.0/gems/s3_website-2.7.2/bin/s3_website:237:in `download_jar'
        from C:/PortableJekyll/ruby/lib/ruby/gems/2.0.0/gems/s3_website-2.7.2/bin/s3_website:220:in `resolve_jar'
        from C:/PortableJekyll/ruby/lib/ruby/gems/2.0.0/gems/s3_website-2.7.2/bin/s3_website:115:in `push'
        from C:/PortableJekyll/ruby/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from C:/PortableJekyll/ruby/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from C:/PortableJekyll/ruby/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from C:/PortableJekyll/ruby/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from C:/PortableJekyll/ruby/lib/ruby/gems/2.0.0/gems/s3_website-2.7.2/bin/s3_website:270:in `<top (required)>'
        from C:/PortableJekyll/ruby/bin/s3_website:23:in `load'
        from C:/PortableJekyll/ruby/bin/s3_website:23:in `<main>'
```
Windows 8.1, just updated Java.

I saw a closed issue that seemed the same, and downloaded the cert file and then did:

```
set SSL_CERT_FILE=C:\PortableJekyll\ruby\cacert.pem.txt
```
which seemed to work, but that didn't help. 

Any ideas? i have unistalled and re-installed s3_website several times.

**Comment by laurilehmijoki** [comment]
This problem is not specific to s3_website. It has to do with Windows and RubyGems and SSL. 

Please reopen this issue if the above assumption is not correct.

**Comment by laurilehmijoki** [comment]
Your error report indicates that you cannot successfully establish an SSL connection to GitHub. Maybe your connection to GitHub is blocked?

**Comment by rdyar** [comment]
yep. I've tried a bunch of the solutions on SO but so far haven't got it to work yet. 

This should be the solution but, but I haven't been able to get it to work yet.

https://gist.github.com/luislavena/f064211759ee0f806c88

Thanks

**Comment by rdyar** [comment]
ah - the problem is downloading the s3_website .jar file - I tried a million and one things to fix the ssl problem, but it is way beyond me, thought I was close a few times.

All the ssl connection is trying to do is download the s3_website.jar file which you can get from the 'release' link. So I just went and got that, renamed it to 's3_website-2.7.2.jar' and put it in the s3_website folder inside the ruby/gems folder.

Works like a champ.

**Comment by rdyar** [comment]
More info on how I fixed this. I just did it to another computer (win 7).

When I tried to update the s3_website gem, it errored with the ssl thing - yesterday on my other computer (win 8.1) it updated no problem, then errored when i tried to push.

I had found this yesterday:
https://gist.github.com/luislavena/f064211759ee0f806c88

which explains some of the problem, though it does not fix it entirely for me. I just did this on my win 7 computer (updated the rubygem file, dropped the new cert in the ssl folder) and then I was able to get past the error when installing the s3_website gem. Then I still got the ssl error when I tried to push, and you can see that it tries to download the jar file - it was in the s3_website gem folder but was 0kb. So I just went to the Release page for this project, downloaded the jar file and changed the name to match the 0kb jar file (which is just adding the version number I think) and dropped it into the s3_website gem folder.

Works great now. phew.

**Comment by david-hoicka** [comment]
Thanks @rdyar, your explanation is really clear, and your solution works great

**Comment by clenemt** [comment]
Same problem here, had to follow instructions from: https://superdevresources.com/ssl-error-ruby-gems-windows/
