### ISSUE TITLE
Support for temporary credentials from ec2 metadata

### ISSUE THREAD

**Issue by cast** [laurilehmijoki/s3_website#143]
You can get temporary security credentials by going to http://169.254.169.254/latest/meta-data/iam/security-credentials/{role-name} on an ec2 instance. Role name you get from http://169.254.169.254/latest/meta-data/iam/info.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

The token needs to be sent as well to allow a successful request with the temporary security credentials.

Perhaps this token could be added as a config/cli attribute which in turn can be added to the credentials when sending requests.

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.
