### ISSUE TITLE
Suggestion: add .ico to default gzip list

### ISSUE THREAD

**Issue by tkrotoff** [laurilehmijoki/s3_website#147]
.html, .css, .js, and .txt files are compressed by default with `gzip: true`.

I suggest to add also .ico: .ico files are not compressed and 99% of websites have a favicon.ico.

I've discovered this by running my website through webpagetest.org.

**Comment by laurilehmijoki** [comment]
Good idea! 

Can you send a PR? The list of automatically compressed file extensions is easy to find from the code base.

**Comment by ianhattendorf** [comment]
I went ahead and submitted a pull request (#148).

**Comment by laurilehmijoki** [comment]
Released in v. **2.8.0**. Thanks @ianhattendorf!
