### ISSUE TITLE
Specify CloudFront price class 

### ISSUE THREAD

**Issue by jponge** [laurilehmijoki/s3_website#150]
`cfg apply` always resets CloudFront distributions to the most expensive class price.

It would be useful to have an option to specify which one we intend on using (http://aws.amazon.com/cloudfront/pricing/)

**Comment by laurilehmijoki** [comment]
Behind the scenes, s3_website uses a tool called [configure-s3-website](https://github.com/laurilehmijoki/configure-s3-website). The tool [lets you define CloudFront configurations in YAML format](https://github.com/laurilehmijoki/configure-s3-website#creating-a-new-distribution-with-custom-settings).

Maybe you can specify the price class with the YAML configuration? Please share your findings if you try out that option.

**Comment by jponge** [comment]
Seems like there is a `price_class` property: https://github.com/laurilehmijoki/configure-s3-website/blob/master/lib/configure-s3-website/cloudfront_client.rb#L180

I'll try and let you know, in which case you could update the documentation accordingly.

**Comment by jponge** [comment]
@laurilehmijoki I confirm that:

```yaml
price_class: PriceClass_100
```

in the `cloudfront_distribution_config` section works great.

Possible values are: `PriceClass_All` (default), `PriceClass_200 ` and `PriceClass_100` (cheapest).

**Comment by laurilehmijoki** [comment]
Cool, thanks for sharing!

You can document your example [here](https://github.com/laurilehmijoki/s3_website/blob/master/additional-docs/example-configurations.md) if you want to.
