### ISSUE TITLE
Add an option to disable CDN invalidations

### ISSUE THREAD

**Issue by jponge** [laurilehmijoki/s3_website#151]
Would it be possible to add a flag to avoid CDN invalidations?

URL invalidation accounts in a free quota of 1000/month, and it can quickly become prohibitive. There are cases where simply waiting for the CDN TTL to expire after a S3 push is acceptable.

**Comment by laurilehmijoki** [comment]
You can disable CloudFront invalidations by removing the `cloudfront_distribution_id` setting from *s3_website.yml*.

**Comment by jponge** [comment]
I meant a flag to disable invalidations over a single run where that would be the intended action.

**Comment by laurilehmijoki** [comment]
Would you prefer a command-line option or a setting in the *s3_website.yml* file?

**Comment by jponge** [comment]
I was thinking of a CLI flag.

**Comment by laurilehmijoki** [comment]
Here is how you can create your own CLI flags with ERB:

File *s3_website.yml*:
```erb
<%
  unless ENV['SKIP_CLOUDFRONT'] == 'true'
%>
cloudfront_distribution_id: YOUR_DIST_ID
<%
  end
%>
```

Once the snippet above is in place, you can call `SKIP_CLOUDFRONT=true s3_website push`, and it will not invalidate any items on your CloudFront distribution.

Does the above snippet help you?

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.
