### ISSUE TITLE
CloudFront origin configuration and HTTPS

### ISSUE THREAD

**Issue by jponge** [laurilehmijoki/s3_website#152]
`s3_website` currently configures a CloudFront distribution with a S3 bucket origin.

However, the _origin protocol policy_ is set by the tool to `Match Viewer` instead of `HTTP only`.

This is a problem because HTTPS connections will then trigger HTTPS connections between CloudFront and S3. This causes an error as S3 buckets configured as websites are only reachable through HTTP.

**Comment by laurilehmijoki** [comment]
If `HTTP only` is *always* the best option for s3_website users, then we should change `Match Viewer` to that.

Can we be sure that it is always the best option?

**Comment by jponge** [comment]
The problem is that S3 does _not_ support HTTPS, so a CloudFront distribution that has a `Match Viewer` policy will always result in an error.

**Comment by laurilehmijoki** [comment]
Okay, now I understand perfectly.

I just [upgraded](https://github.com/laurilehmijoki/configure-s3-website/commit/304af434c3a68ece77df1433ac61f4d58c6e57b4) the configure-s3-website gem and [added](https://github.com/laurilehmijoki/s3_website/commit/d8476195fe5791cfd39698ce91af3248875c0843) it into the s3_website version **2.8.1**. 

Does that version solve this issue?

**Comment by jponge** [comment]
Works great, thanks!

**Comment by laurilehmijoki** [comment]
:thumbsup:
