### ISSUE TITLE
Pushing from within Rails app

### ISSUE THREAD

**Issue by bosskovic** [laurilehmijoki/s3_website#153]
Hi. First of all, thanks for the great gem!

I need to do the pushing via Rails application (probably in a background job), and I need to have some response that I can store/show.

One obvious solution is to call the shell command `s3_website push` and parse its output.

Is it possible to (easily and cleanly) run the push from ruby? What would I need to require and instantiate from the gem?

**Comment by laurilehmijoki** [comment]
Hi @bosskovic!

One option for you is to use the version 1 of this gem. It has [documentation](https://github.com/laurilehmijoki/s3_website/tree/1.x) on how to use it as a library. However, the version 1 is no longer under active development. It might be sufficient for you, though.

Another option is to call the `s3_website push` command as you mentioned. Regarding this option: what information would like to parse from the output? Maybe we should add a possibility to format the standard output as JSON. What do you think about this?

**Comment by bosskovic** [comment]
Hi, thanks for the response, I will check the old version.
The information that would suffice for me is what is already given as the output to the console - whether the push succeeded, what files were changed, etc, but in a structured form. JSON would be great.

**Comment by laurilehmijoki** [comment]
Out of curiosity, what do you plan to do with the statistics?

**Comment by bosskovic** [comment]
The static site is generated out of the dynamic content by the user, and all I need to show the user is success/fail. I need to log the rest in the case of the failure.

For anyone else needing something similar, here is a quick solution:

output = Dir.chdir(dir_with_s3_website_yml) { `s3_website push` }
#writing log to file
File.open(log_path, 'w') { |f| f.write(output) }
success = output.split(/\n/).last =~ /^[info] Successfully pushed the website/

**Comment by laurilehmijoki** [comment]
Here's a more robust way to determine whether `s3_website push` succeeded or not:

```ruby
output = Dir.chdir(dir_with_s3_website_yml) { `s3_website push` }
push_succeeded = $? == 0
```

The advantage of that solution is that it does not depend on the output but the process exit code. s3_website will exit with non-zero status if something went wrong during `push`.

**Comment by bosskovic** [comment]
Thanks!

**Comment by laurilehmijoki** [comment]
Closing the issue. Please re-open if needed.
