### ISSUE TITLE
invalid or corrupt jar file in 2.8.6 

### ISSUE THREAD

**Issue by oknowwhat** [laurilehmijoki/s3_website#157]
Cannot push site via s3_website push due to an error invalid jar file 

site root>s3_website push
[info] The jar file is corrupted. (Expected checksum a5dff84ae39e23dae2a6fd3edfa
51823 but got d41d8cd98f00b204e9800998ecf8427e.)
[info] Downloading https://github.com/laurilehmijoki/s3_website/releases/downloa
d/v2.8.6/s3_website.jar into C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/s3_website-2
.8.6/s3_website-2.8.6.jar

not sure what is causing this

**Comment by laurilehmijoki** [comment]
If downloading the *.jar* file fails, then you will receive the *jar file is corrupted* message.

Try running `s3_website push` again. It re-downloads the *.jar* file.

Does this solve your problem?

**Comment by oknowwhat** [comment]
nope, jar file still corrupt

**Comment by laurilehmijoki** [comment]
Thanks for the feedback @oknowwhat ! Unfortunately right now I don't have an idea what could cause the corruption. If you or someone else can point to a possible cause, please chime in.

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.
