### ISSUE TITLE
Deleted log/access?

### ISSUE THREAD

**Issue by yitang** [laurilehmijoki/s3_website#159]
Hi, after `s3_website push`, I get 

````
[succ] Deleted log/access_log-2015-05-06-18-51-15-B7063409503F326B
[succ] Deleted log/access_log-2015-05-06-19-38-13-C7D791D900CC43E5
```

What are those log files? Do I need to worry about the deletion?

**Comment by Joshfindit** [comment]
I can answer the first question:
Those log files are access logs created by Amazon when a visitor accesses your site.

Here's an example:

    588242fb6ce3e1398e23835addd85234ace... domain.ca [25/Jul/2015:20:57:53 +0000] 37.157.x.x - AD61B667... WEBSITE.GET.OBJECT index.html "GET / HTTP/1.1" 200 - 4060 4060 41 41 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/98 Safari/537.4 (StatusCake)" - ```

*This is StatusCake checking in.*

Note: You usually explicitly choose to enable logging when you set up an S3 bucket, and it's a setting you can access in the S3 control panel.

The second question of **do you need to worry about it**: Now that you know what they are, that's up to you.

**Comment by Joshfindit** [comment]
Personally, **I don't want s3_website to delete the logs**.

How can we stop it?

**Comment by laurilehmijoki** [comment]
Thanks for bringing this up @Joshfindit.

Are there any other users who would like s3_website to automatically ignore **logs**?

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.

**Comment by Joshfindit** [comment]
Is there anyone who *doesn't* want logs to be automatically ignored?
