### ISSUE TITLE
Put website in subdirectory of S3 bucket?

### ISSUE THREAD

**Issue by csu** [laurilehmijoki/s3_website#160]
Is there a way to set s3_website to upload the website to a subdirectory of a S3 bucket? For example, if my website and my blog are separate Jekyll instances, is there a way I could get s3_website to upload my blog to the /blog/ directory of my website bucket?

**Comment by laurilehmijoki** [comment]
Hi @csu. At the moment this is not possible.

**Comment by csu** [comment]
Alright, thanks.

**Comment by laurilehmijoki** [comment]
This is actually a good improvement idea, thanks for bringing this up. Let's keep this issue open – maybe someone will submit a pull request.

**Comment by bosskovic** [comment]
This would be useful for us too. Any chance for it being implemented soon? :-)

**Comment by laurilehmijoki** [comment]
@bosskovic and @csu: may I ask why the subdirectory setting would solve your problem?

In other words, what use case(s) cannot be fulfilled without this subdirectory setting?

**Comment by bosskovic** [comment]
I have a number of directories in the root that need to be updated separately. If the list of the directories was definite and if it would not change, I could prior to each push dynamically generate the yaml file with all other directories excluded, but it is too risky this way (keeping track of the directories elsewhere and using that info to build the regex).

Additionally, publishing to specific directory would make it possible to set privileges for specific users to publish to specific directories (otherwise all users need to have access to root).

**Comment by laurilehmijoki** [comment]
Hello @bosskovic, the branch https://github.com/laurilehmijoki/s3_website/tree/s3-key-prefix now contains an implementation for the subdirectory feature. Please try it out.

Here's how you can try it:

First, ensure that you have a [JDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) installed.

Second, use the `s3_key_prefix` in your *s3_website.yml* file. It's documented here: https://github.com/laurilehmijoki/s3_website/tree/s3-key-prefix#s3-website-in-a-subdirectory-of-the-bucket.

Third, run the following commands in your terminal:

```sh
cd /tmp
git clone https://github.com/laurilehmijoki/s3_website --branch s3-key-prefix
cd YOUR_TEST_WEBSITE
/tmp/s3_website/bin/s3_website push
``` 

Finally, please tell me about your experience.

If it works for you, I will merge it into master and release it.

**Comment by laurilehmijoki** [comment]
In that branch, I found a bug. `s3_website push` deletes files when it should not. Hold your horses, I'll try to fix that.

**Comment by bosskovic** [comment]
Thanks for implementing it! We already did it via a workaround (adding multiple origins to a single distro, one per each directory). I will test this and migrate at the beginning of the next cycle and report here.
Thanks again.

**Comment by Laurian** [comment]
I just tried the s3-key-prefix thing in Codeship and I get 
```
/home/rof/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- thor (LoadError)
	from /home/rof/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/rof/src/github.com/trint-it/trint-app/s3tmp/s3_website/lib/s3_website.rb:2:in `<top (required)>'
	from /home/rof/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/rof/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./s3tmp/s3_website/bin/s3_website:3:in `<main>'
```

**Comment by Laurian** [comment]
Ah, running `gem install s3_website` before the above git clone/etc. solves the missing dependencies; sorry, I'm not a Ruby person.

**Comment by Laurian** [comment]
@laurilehmijoki `s3-key-prefix` works for me, I deploy to S3 versions of my static webapp in folders per commit hash to have a way to test various versions, etc.

**Comment by atomjack** [comment]
@laurilehmijoki This works for me as well. Kiitos!

**Comment by laurilehmijoki** [comment]
Released in version **2.11.0**.

If you discover ways to improve the [documentation](https://github.com/laurilehmijoki/s3_website#s3-website-in-a-subdirectory-of-the-bucket) on this new `s3_key_prefix` setting, please send a pull request.

**Comment by bosskovic** [comment]
We migrated to this feature from a workaround we had in place and it works perfectly.
@laurilehmijoki thank you for your help and effort!

**Comment by shulamit74** [comment]
It still does'nt work for me. it pushes the folder to the root of the bucket. 
I'm using s3_website with bitbucket pipeline . that my yml file :
```
s3_bucket: my-bucket
s3_endpoint: us-east-1
s3_id: "<%= ENV['S3_ID'] %>"
s3_secret: "<%= ENV['S3_SECRET'] %>"
site: site
s3_key_prefix: dev

**Comment by laurilehmijoki** [comment]
Given

```yaml
s3_key_prefix: dev
```

and invoking `s3_website push`,

my site gets pushed under the `dev` folder. I'm out of ideas why it works for me but not for you. Any thoughts on this?

**Comment by shulamit74** [comment]
Okay i found my problem. I'm was using your code with bitbucket pipelines and a costume Docker image . Now i see it wasn't downloading the lastest version of the jar file. I fixed it and now it works perfectly :) thank you!
