### ISSUE TITLE
Consider using the wildcard invalidation feature of CloudFront

### ISSUE THREAD

**Issue by laurilehmijoki** [laurilehmijoki/s3_website#161]
Benefits

* lower costs to users
* a more simpole implementation

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html

**Comment by jumoel** [comment]
:+1:

**Comment by NoSync** [comment]
Hey Lauri, this would be rather cool indeed. Hopefully it can be implemented soon. :-)

**Comment by NoSync** [comment]
Best would be the ability to set something like a threshold - ie, if more than X items would have to be invalidated, switch to wildcard invalidation.

**Comment by j15e** [comment]
+1 that it would nice because of amazon pricing. It cost a lot to invalidate each files individually VS using a wildcard.

> A path that includes the * wildcard counts as one path even if it causes CloudFront to invalidate thousands of objects.

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#PayingForInvalidation

It ends up costing me a lot to deploy a static website (it cost me ~50$ in a month in which we made a lot of deployments).

**Comment by basex** [comment]
+ 1 for this. There could be an option to invalidate everything with a wildcard instead of having to pay $0.005 per path requested for invalidation.

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#PayingForInvalidation

**Comment by tiagomatos** [comment]
+1 here. It's getting to expensive for us.

**Comment by laurilehmijoki** [comment]
Released in **2.14.0**, please see documentation at <https://github.com/laurilehmijoki/s3_website#invalidating-all-cloudfront-resources-wildcard-invalidation>.

The commit is here: <https://github.com/laurilehmijoki/s3_website/commit/7089b3882083d478f5ca41648f4a381636fad6a8>.

Feedback appreciated.
