### ISSUE TITLE
Reading of env-variables without .env-file

### ISSUE THREAD

**Issue by PureW** [laurilehmijoki/s3_website#162]
Would it be possible to read the system's env-variables without creating a file containing the needed variables? That kind of defeats the purpose of having config in env-variables.

Essentially, since I already have AWS_DEFAULT_REGION etc in my env-variables, I don't want to define them on disk one more time in an .env-file.

**Comment by laurilehmijoki** [comment]
Yes, it should be possible. Try adding the following [ERB](http://en.wikipedia.org/wiki/ERuby) snippet in your *s3_website.yml* file:

```erb
s3_endpoint: <%= ENV['AWS_DEFAULT_REGION'] %>
```

Does that work for you?

**Comment by PureW** [comment]
Hi, I'm afraid not, this is the top of my s3_website.yml-file:
    
    head s3_website.yml                                                                                               1 ↵
    s3_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    s3_secret: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

When I try to apply the config I get the following:

    s3_website cfg apply                
    Applying the configurations in s3_website.yml on the AWS services ...
    AWS API call failed:
    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>A33EA587312A1836</RequestId><HostId>cE9b6uKo1stihpjTSxnkEa7B7TxHDtQSNK/611Cm58WYu7ybxRWoZIEPwRNEYrNt14TvuIujvhY=</HostId></Error> (GenericError)

And the env-vars should be working correctly as the aws-cli can authorize using them.

On a side-note, maybe I named the ticket wrong as I read the documentation on the frontpage to mean that only env-vars in a file in project-dir were parsed.

    S3_website implements supports for reading environment variables from a file using the dotenv gem. You can create a .env file in the project's root directory to take advantage of this feature. Please have a look at dotenv's usage guide for syntax information. )

**Comment by laurilehmijoki** [comment]
What AWS Region you are using? s3_website does not yet support *eu-central-1*, in case you are using it.

**Comment by PureW** [comment]
Ahh that's it then. Will the *eu-central-1* be possible anytime soon?

**Comment by laurilehmijoki** [comment]
As far as I know nobody is working on it at the moment.

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.
