### ISSUE TITLE
Peer not authenticated errors

### ISSUE THREAD

**Issue by pronvit** [laurilehmijoki/s3_website#163]
I'm always getting `Unable to execute HTTP request: peer not authenticated` errors on Ubuntu with `OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.10.2)` but everything works fine on OS X with `Java(TM) SE Runtime Environment (build 1.7.0_25-b15)`. I suppose this is related to SSL and S3-style hostnames, but how does it ever work then?

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.

**Comment by ekristen** [comment]
I'm seeing this issue, can't figure out why.

**Comment by laurilehmijoki** [comment]
Will upgrading Java help?
