### ISSUE TITLE
cloudfront logging?

### ISSUE THREAD

**Issue by joelburget** [laurilehmijoki/s3_website#164]
I'd like to log my cloudfront stats. To do so I need to specify an S3 bucket to log to. Perhaps we can add such an option?

**Comment by pathawks** [comment]
Wouldn’t it be easier to just do this through the AWS console? It’s not something that’s likely to change often.

**Comment by joelburget** [comment]
My understanding was that the configuration would be overwritten next time I deploy. This stuff is all written by `s3_website`, right (in Particular, "Log Bucket")?

![screenshot 2015-06-03 11 55 32](https://cloud.githubusercontent.com/assets/310981/7952398/6683868a-09e7-11e5-89e0-26efdc4155bc.png)

**Comment by laurilehmijoki** [comment]
Hello. `s3_website push` does not modify the CloudFront settings. Only `s3_website cfg apply` does.

**Comment by joelburget** [comment]
Ah, I see. That fixes my problem!
