### ISSUE TITLE
Setting custom headers

### ISSUE THREAD

**Issue by bosskovic** [laurilehmijoki/s3_website#165]
Hello,
in addition to setting max_age, we would like to be able to set the header for all uploaded files to:

cache-control: public, no-transform, max-age=1200, s-maxage=1200

Is that possible with the gem at the moment? If not, is there a way to execute our own custom action that does that via aws api after the upload is done but before invalidation starts? Perhaps a callback, or is there a way to manually start the cloud front invalidation instead of automatically?

Thanks

**Comment by laurilehmijoki** [comment]
Hello @bosskovic. At the moment s3_website does not have the features you mention.

We could, however, add a new setting into *s3_website.yml*. The setting could look like this:

```yaml
cache_control: public, no-transform, max-age=1200, s-maxage=1200
```

This new `cache_control` setting and the old `max_age` should probably be mutually exclusive.

What do you think?

PS. Here is the place in code where the cache control header is set: https://github.com/laurilehmijoki/s3_website/blob/master/src/main/scala/s3/website/S3.scala#L80.

**Comment by bosskovic** [comment]
hi @laurilehmijoki 

thanks for the express reply! Your suggestion would be perfect for what we need. I think it is ok that it would override max_age, since it is its superset.

**Comment by laurilehmijoki** [comment]
@bosskovic I just released the version **2.9.0** which contains this feature. Please try it out and tell me if it works for you.

The commit is here: https://github.com/laurilehmijoki/s3_website/commit/213b7c6f9bb4f3a50eb1299cc5f3401ab914af67. I appreciate feedback.

**Comment by bosskovic** [comment]
hi @laurilehmijoki 

thanks for pushing the new version so quickly. Would it be possible to add more granularity to cache_control, the same way as max_age? At the moment we have some resources that rarely change (html, images, js libs...) and some that do change fairly often (json-s), and we need a different cache control settings for them.

**Comment by laurilehmijoki** [comment]
Sure. Try out the version **2.10.0**. Here's the updated documentation on `cache_control`: https://github.com/laurilehmijoki/s3_website#cache_control.

**Comment by bosskovic** [comment]
hi @laurilehmijoki 

Everything is perfect now, thanks a lot for your help! I will close this issue now.
