### ISSUE TITLE
[Feature] Redirect xyz/index.html to xyz

### ISSUE THREAD

**Issue by alexw23** [laurilehmijoki/s3_website#168]
Just wanted to put out a feature request, I find it frustrating that you can access a path by either `/contact` and `/contact/index.html`. This means it could be indexed twice - and may also play up with analytics.

S3 has routing rules that can handle the task of routing `/contact/index.html` to `/contact` as seen below

	<RoutingRules>
	    <RoutingRule>
	    <Condition>
	      <KeyPrefixEquals>contact/index.html</KeyPrefixEquals>
	    </Condition>
	    <Redirect>
	      <ReplaceKeyPrefixWith>contact/</ReplaceKeyPrefixWith>
	    </Redirect>
	    </RoutingRule>
	</RoutingRules>

It just needs to be automated with s3_website. I assume there would be a config of some sort you can turn on that would apply these routing rules automatically?

**Comment by laurilehmijoki** [comment]
Would [canonical URLs](https://support.google.com/webmasters/answer/139066) help you?

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.
