### ISSUE TITLE
Jar file keeps redownloading

### ISSUE THREAD

**Issue by code-tree** [laurilehmijoki/s3_website#174]
Every time I run s3_website it seems to redownload the jar file. If I haven't turned off my computer it just accesses it from /tmp, except that gets cleared regularly, so it keeps getting redownloaded.

Is it supposed to get saved somewhere? Any idea how to stop this happening?

```
[info] Downloading https://github.com/laurilehmijoki/s3_website/releases/download/v2.10.0/s3_website.jar into /tmp/s3_website-2.10.0.jar
```

thanks!

**Comment by code-tree** [comment]
I worked out that it defaults to /tmp when it doesn't have permission to save it in the correct location.

Would it be better to ask the user for root permissions when this occurs, rather than simply storing it in /tmp?

For anyone else with this problem:
```sudo mv /tmp/s3_website-2.10.0.jar /var/lib/gems/2.1.0/gems/s3_website-2.10.0/```

**Comment by laurilehmijoki** [comment]
I agree: asking for write permission is a good idea. Pull request appreciated.

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.

**Comment by assimovt** [comment]
@laurilehmijoki Is it possible to pre-download the jar file so the push operation won't need to do it at all?

**Comment by laurilehmijoki** [comment]
@assimovt yes it is. Here's how to do it:

```bash
S3_WEBSITE_VERSION=2.12.1
gem install s3_website -v ${S3_WEBSITE_VERSION}
curl -L https://github.com/laurilehmijoki/s3_website/releases/download/v${S3_WEBSITE_VERSION}/s3_website.jar > `gem environment gemdir`/gems/s3_website-${S3_WEBSITE_VERSION}/s3_website-${S3_WEBSITE_VERSION}.jar
```

After running the above commands, you can run `s3_website push` and it will not download the jar file.

**Comment by assimovt** [comment]
Thanks @laurilehmijoki

**Comment by code-tree** [comment]
Is it possible to execute the downloading code on install, instead of on push? As I sudo install initially, then push as unprivileged. I'm not sure if that is the same for others or not.

**Comment by laurilehmijoki** [comment]
Maybe yes. I'm not familiar with the quirks of the Ruby gem post-install hooks, but we could do something like this: http://blog.costan.us/2008/11/post-install-post-update-scripts-for.html?m=1. What do you think?

Anyway, usually you should not need to use sudo when installibg Ruby gems. Have you considered using rbenv or rvm?

**Comment by code-tree** [comment]
Sounds good, or even including it in the actual ruby gem somehow? Either way, it is nice to have it fully installed initially.

I usually use python envs for my own development, but haven't become familiar with ruby's yet.

**Comment by laurilehmijoki** [comment]
The last time I checked the RubyGems system had an upper limit to the size of the gem. Hence I chose to place the jar file into GitHub. Maybe there no longer is an upper limit?
