### ISSUE TITLE
Alternative way to set credentials

### ISSUE THREAD

**Issue by halk** [laurilehmijoki/s3_website#177]
I was just about to push my blog repository to github when I saw the S3 credentials in s3_website.yml. 

I have read the README which mentions to set s3_website.yml into the files to ignore. That is I think not an appropriate solution since this file is not only containing these credentials but also essential configuration and redirects which I believe are something to be versioned really. If it needs to be in .gitignore, at least the README should suggest to keep a distributable version without the credentials. Also once committed, it is not that convenient to remove all traces of this file and you usually are better with resetting the credentials.

This might not be a big deal for most users but it'd be great to have an alternative way to set the credentials like ENV variables.

**Comment by laurilehmijoki** [comment]
Here's how you can use ENVs in *s3_website.yml*: https://github.com/laurilehmijoki/s3_website#using-environment-variables.

**Comment by halk** [comment]
Thanks! That's fine. Skipped that part I think while reviewing the README and seen the .gitignore instructions.
