### ISSUE TITLE
"Authorization header is invalid" on push

### ISSUE THREAD

**Issue by thom-nic** [laurilehmijoki/s3_website#178]
this happened after I attempted a second push, after the initial push succeeded.

```bash
$ bin/s3_website push
[info] Deploying /Users/thom/dev/voltserver/voltserver.com/_site/* to voltserver.com
[fail] Failed to fetch an object listing (Authorization header is invalid -- one and only one ' ' (space) required (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 9EFD418F0905879F))
[info] Summary: 2 operations failed.
```

**Comment by laurilehmijoki** [comment]
Closing as cannot-reproduce. Please reopen if needed.

**Comment by thom-nic** [comment]
I actually wrote my own plugin [thom-nic/jekyll-s3_deploy](https://github.com/thom-nic/jekyll-s3_deploy) which is a pure-ruby solution.  Uses the official AWS SDK for Ruby.  Supports content-encoding but not CloudFront just yet...

**Comment by laurilehmijoki** [comment]
Nice!

**Comment by shinwang1** [comment]
I got this error when I made a mistake in my yml file.
Instead of `s3_id: <%= ENV['S3_ID'] %>`
I did `s3_id: <$= ENV['S3_ID'] %>`

**Comment by thom-nic** [comment]
Yeah the lesson learned is this error probably means an AWS key wasn't set correctly.  Error message could be better.
