### ISSUE TITLE
Vary header is missing?

### ISSUE THREAD

**Issue by sparanoid** [laurilehmijoki/s3_website#180]
From [AWS documentation](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#ResponseCustomContentNegotiation) says it supports `Vary` header (`Accept-Encoding` only), so does s3_website support it?

**Comment by pathawks** [comment]
What good would it do?

S3 will serve the same file no matter what the request’s `Accept-Encoding` is…

**Comment by sparanoid** [comment]
@pathawks I know it's not that important but several benchmark tools like PageSpeed Insights suggest Vary header should be specified.

**Comment by pathawks** [comment]
But it would only slow the site down, because it would make a cache hit less likely.

Do you understand?

**Comment by laurilehmijoki** [comment]
Closing as willnotfix. Please reopen if needed.
