### ISSUE TITLE
missing version when creating IAM policy

### ISSUE THREAD

**Issue by msonsona** [laurilehmijoki/s3_website#185]
I've copy-pasted the policy for the S3 credentials, as specified in [your docs](https://github.com/laurilehmijoki/s3_website/blob/master/additional-docs/setting-up-aws-credentials.md)

but when I validate the policy using the AWS console, it gives an error saying the version is missing. Following [their docs](http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_grammar.html) on the issue, I've added the following line and it seems to validate just fine:
```
"Version": "2012-10-17",
```

Just opening the issue to see if you want to update the docs accordingly :wink:

**Comment by laurilehmijoki** [comment]
Hello @msonsona! Can you send a pull request that contains your fix? Thanks!
