### ISSUE TITLE
Website will not push

### ISSUE THREAD

**Issue by ReadyP1** [laurilehmijoki/s3_website#192]
I have a basic Jekyll site that I want to get running on an S3 bucket. I went ahead and edited the config file with my access credentials, and applied CloudFront. Whenever I try to push, I get the following error (which I had `cmd` pipe to a txt file):

```
[[34minfo[0m] The jar file is corrupted. (Expected checksum 484de7f15e52195c16dd3876bf8b2d64 but got d41d8cd98f00b204e9800998ecf8427e.)
[[34minfo[0m] Downloading https://github.com/laurilehmijoki/s3_website/releases/download/v2.12.2/s3_website.jar into C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/s3_website-2.12.2/s3_website-2.12.2.jar
```
I also got a bunch of errors in the command line; look below.

![s3_website error 1](https://cloud.githubusercontent.com/assets/6777358/10711258/8b6829e8-7a43-11e5-95eb-134f07eccbd8.jpg)

**Comment by laurilehmijoki** [comment]
@ReadyP1 will [this issue](https://github.com/laurilehmijoki/s3_website/issues/142) help you?

**Comment by ReadyP1** [comment]
Yep, it did! Thanks!
