### ISSUE TITLE
[Documentation] describe the process of updating a page

### ISSUE THREAD

**Issue by csillag** [laurilehmijoki/s3_website#193]
Hi.

From reading the README file, it's unclear to me what happens when I run "push" subsequently after a change.

Will it always upload the whole site again, overwriting the old one?

Or will it do some smart syncing, rsync-style? 

Do I need to care about this, or I can just run push again and again, and expect
it to keep by s3 bucked in sync?

It would be great if a few sentences could be added about this.

**Comment by laurilehmijoki** [comment]
Hi, `s3_website push` calculates the difference between your local website and the website on the S3 bucket. Then it updates the changed files, uploads the new files and deletes the obsolete files.

In other words, if you just wish to synchronise your local website with the S3 website, just call `s3_website push`.

Please send a pull request if you invent a handy way of answering to your own questin :)

**Comment by csillag** [comment]
> s3_website push calculates the difference [...]  if you just wish to synchronise your local website [...]  just call s3_website push.

That's perfect.

> Please send a pull request if you invent a handy way of answering to your own questin :)

OK, I will. (Meanwhile, I realized that won't be able to use this project until https://github.com/laurilehmijoki/s3_website/issues/126 is fixed.)

**Comment by csillag** [comment]
> Please send a pull request if you invent a handy way of answering to your own questin :)

See my PR https://github.com/laurilehmijoki/s3_website/pull/194

**Comment by laurilehmijoki** [comment]
Merged, thanks @csillag!
