### ISSUE TITLE
Change in S3/Cloudfront policy makes Cloudfront not work

### ISSUE THREAD

**Issue by RNCTX** [laurilehmijoki/s3_website#197]
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-cloudfront-distribution.html

*The name of your Amazon Route 53 hosted zone (such as example.com) must match an alternate domain name in the CloudFront distribution. You cannot route queries to the CloudFront domain name for your distribution (such as d111111abcdef8.cloudfront.net).*

I ran your script yesterday on a new domain, and it worked great except for the above.  You must manually create alternate CNAMEs for your domain in Cloudfront, otherwise Cloudfront will refuse the connection(s).

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.
