### ISSUE TITLE
add ability to specify a config file, not a directory where config file is located

### ISSUE THREAD

**Issue by AndreiRailean** [laurilehmijoki/s3_website#199]
I maintain configs for staging and production and as currently done, these configs have to be in separate folders. Ideally, I'd keep these files together and name them differently.

PS: s3_website is great tool, thanks!

**Comment by laurilehmijoki** [comment]
Thanks for bringing up your experience.

I agree: there should be an option to point to the exact config files, not just the --config_dir.

Alternatively, you can use the environment variables to define the production/test differences.

**Comment by laurilehmijoki** [comment]
Closing as duplicate with #223.
