### ISSUE TITLE
The jar file is corrupted

### ISSUE THREAD

**Issue by victorbstan** [laurilehmijoki/s3_website#201]
I get the following error when trying to do: `s3_website push`

```
[info] The jar file is corrupted. (Expected checksum 484de7f15e52195c16dd3876bf8b2d64 but got d41d8cd98f00b204e9800998ecf8427e.)

Downloading https://github.com/laurilehmijoki/s3_website/releases/download/v2.12.2/s3_website.jar into /Users/victorstan/.rvm/gems/ruby-2.2.3/gems/s3_website-2.12.2/s3_website-2.12.2.jar
```

**Comment by emory** [comment]
Likewise! And my fetch fails because of a certificate validation issue that may or may not be related.

**Comment by rdyar** [comment]
what os? on windows I have issues but they are easy to bypass. In my gems/s3_website-2.12.2 folder the .jar file is 0kb when I do the install or gem update for s3_website.

All I do is go to the 'Releases' tab at the top of the main page and copy the .jar file from there (~44mb) and put it in the folder - the names are different so you have to rename it to what the 0kb file is in the gem folder. This seems to be related to the certificate validation for me. Works like a charm though.

**Comment by david-hoicka** [comment]
Thanks @rdyar , your solution works great

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.

**Comment by espen** [comment]
I had this issue. In my case it was due to the download being aborted. The next time I ran the command it then complained about jar file being corrupted. Reinstalling the gem fixed it (I was then able to download the jar without any interruption).
