### ISSUE TITLE
letsencrypt.org support to generate and set SSL with cloudfront

### ISSUE THREAD

**Issue by riyaz** [laurilehmijoki/s3_website#202]
letsencrypt.org allows to generate free SSL certificates using command line, it would be nice if we can have support for setup and renewal for SSL certificates with cloudfront.

Ref : https://nparry.com/2015/11/14/letsencrypt-cloudfront-s3.html

**Comment by abesto** [comment]
Not sure if it's useful, but: this was one of my first thoughts when learning about `s3_website`. This would be awesome.

**Comment by chrismytton** [comment]
https://github.com/dlapiduz/letsencrypt-s3front is an example of this done in Python. I presume doing it in Ruby will be a bit trickier as the official [letsencrypt client](https://github.com/letsencrypt/letsencrypt) is written in Python and letsencrypt-s3front is written as a plugin.

**Comment by pathawks** [comment]
It would probably be easier and more convienient to just use AWS Certificate Manager instead.

**Comment by jhabdas** [comment]
When adding SSL to my S3 website set-up using this wonderful gem I'd [originally used](https://habd.as/pagespeed-100-with-jekyll-s3-and-cloudfront/#extra-credit-add-ssl-to-your-cloudfront-distribution) Let's encrypt because I found a good tutorial on the Web. But now that I've seen @pathawks comment, the AWS Certificate Manager seems like the obvious choice. Greatly looking forward to seeing support added @laurilehmijoki! 😻

**Comment by laurilehmijoki** [comment]
How would you integrate AWS Certificate Manager with `s3_website`?

**Comment by jhabdas** [comment]
Perhaps I misunderstood Pat's comment followed by the enhancement label addition. Personally I have no idea. But I like the idea of using this Gem to manage/automate SSL certs if at all possible as I know I personally am going to hit friction when when I'm required to renew my Let's Encrypt cert given the amount of manual steps I had to follow.

**Comment by pathawks** [comment]
I use AWS Certificate Manager for my site. Nothing in `s3_website` needs to change to use it, so long as you are comfortable with the AWS Console.

**Comment by jhabdas** [comment]
@pathawks indeed ACM was way easier (and more convenient) for adding an SSL cert than Let's Encrypt once I needed a renewal. Two caveats I was lucky enough not to encounter, however, where a) you must be using an elastic load balancer (e.g. CloudFront) and, where most will probably get tripped up, I'd wager, is that you must have SES wired up to send emails to someone at the domain (or at least to dump them in an S3 bucket so the cert can be authorized). For anyone looking here's [a method for getting SES set-up to forward emails to Google Inbox](https://habd.as/serverless-email-forwards-ses-lambda-crash-course/).

**Comment by jhabdas** [comment]
@riyaz or @laurilehmijoki could you close this issue or mark it as stale?
