### ISSUE TITLE
1.x Warning: "Digest::Digest is deprecated; use Digest"

### ISSUE THREAD

**Issue by pathawks** [laurilehmijoki/s3_website#206]
In **1.x**, just before invalidating Cloudfront items, I get the following warning:

```text
Digest::Digest is deprecated; use Digest
```

This is fixed by laurilehmijoki/simple-cloudfront-invalidator#2

**Comment by laurilehmijoki** [comment]
I just released the version [1.1.0](https://github.com/laurilehmijoki/simple-cloudfront-invalidator/commit/0fce84197b05eb4a7f6c13f1ce83c770588da0b2) of the gem `simple-cloudfront-invalidator`. Thanks for the patch, by the way!

If you now update your version 1 s3_website gem dependencies, the warning should disappear.
