### ISSUE TITLE
`no-cache; max-age=0` vs `no-cache, max-age=0`

### ISSUE THREAD

**Issue by pjanik** [laurilehmijoki/s3_website#208]
CloudFront doesn't want to update my files, even though I've set max-age to 0 in s3_webiste config.
Files uploaded by old version of s3_website work as expected. I've noticed that that files uploaded by the latest version use `no-cache; max-age=0` header while old version was setting `no-cache, max-age=0`.
Not sure about correct and/or accepted format (would need to dig into some specs), but comma seems to be widely used. I haven't found examples with semi-colon. 
Not sure, but maybe CloudFront gets confused and uses default TTL instead of max-age value?
Anyone experiencing similar issues or able to replicate it?

**Comment by laurilehmijoki** [comment]
Thank you @pjanik for pointing out this bug. You are right: the separator in `Cache-Control` should be `,`, _not_ `;`.

I've just released the fix in the version **2.12.3**.

The commit is [here](https://github.com/laurilehmijoki/s3_website/commit/294e0e771176275327c13ea1fd75e6a1e4bb7c29).
