### ISSUE TITLE
s3_website.yml file gets added to the _site folder by default (jekyll)

### ISSUE THREAD

**Issue by stroupaloop** [laurilehmijoki/s3_website#210]
From a security perspective, there's a security risk of dumping the s3_website.yml file into the _site folder, since that folder is typically completely uploaded to S3.

In the case where s3_website fails to upload and the user defaults to uploading via AWS, if the user uploads the _site folder, it will also dump in the s3_website.yml file. The developer should NOT do this BUT having it there by default is a process security issue.

**Comment by stroupaloop** [comment]
Following up on this, additional documentation should be included in the README.md to instruct them to remove the s3_website.yml from being built by jekyll.

Specifically, adding this line into the _config.yml file

    exclude:
      - s3_website.yml

**Comment by manabusakai** [comment]
I think that's a good idea :+1:

**Comment by vietqhoang** [comment]
This seems to be referencing to Jekyll setups?

The project can be used in many different static blog engines. I just wasn't sure what the issue was referencing to when I first saw the issue.

I know Middleman doesn't have this issue since the s3_website.yml is located outside the scope of the source directory.

**Comment by laurilehmijoki** [comment]
The code at https://github.com/laurilehmijoki/s3_website/blob/a17868b3bdd498d0331c48078dc9b67455e9264a/src/main/scala/s3/website/model/push.scala#L135 attempts to always prevent uploading of s3_website.yml. Is there a bug?

**Comment by stroupaloop** [comment]
It's not a bug per say but a process security issue which can be resolved with a modification to the _config.yml file for jekyll sites using the gem.

If s3_website breaks and the user has to default to uploading _site folder manually to S3, they would be adding s3_website.yml file because it's getting packaged into the jekyll build process (root file) and dumped into the _site folder.

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen or submit a pull request if needed.
