### ISSUE TITLE
Excluding .txt files from upload is ignored and the files uploaded

### ISSUE THREAD

**Issue by wgx** [laurilehmijoki/s3_website#211]
I have

`exclude_from_upload: .txt`

In my s3_website.yml - but files with *.txt in the root are still being uploaded on push.

**Comment by laurilehmijoki** [comment]
Hi @wgx, unfortunately I cannot repeat this problem.

Here's how I tested this: I have the file *hello.txt*.

*s3_website.yml*:
```yaml
exclude_from_upload: .foo
```
`s3_website push` output:
```
[succ] Created hello.txt (public, max-age=120 | text/plain; charset=utf-8 | gzip)
```
When I change the config to
```yaml
exclude_from_upload: .txt
```
... and run `s3_website push`  for the second time, the output is
```
[succ] Deleted hello.txt
```
When I run `push` for the third time, the output is
```
[info] Summary: There was nothing to push
```

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.
