### ISSUE TITLE
Multiple Alternate Domain Names in cloudfront

### ISSUE THREAD

**Issue by xtuc** [laurilehmijoki/s3_website#212]
I have multiple CNAME in a cloudfront distribution. I've tried to put all my domain in a string separated with commas but the AWS API rejected it.

Thanks in advance,
Sven.

**Comment by laurilehmijoki** [comment]
Hi! Will https://github.com/laurilehmijoki/s3_website/blob/master/additional-docs/example-configurations.md help you? There's doc on multiple CNames.

**Comment by xtuc** [comment]
Much thanks, it works.
I think you should add a link into the root README.

On AWS console, the CName input allows commas separated values. The CloudFront API doesn't seems to support it.

**Comment by laurilehmijoki** [comment]
Thanks for the feedback. Care to submit a PR on the readme amendment?
