### ISSUE TITLE
How to check if cache control is enabled?

### ISSUE THREAD

**Issue by iloveip** [laurilehmijoki/s3_website#214]
Hi there,

I added the following code to my `s3_config.yml` file in Jekyll site:

```
max_age:
  "css/fonts/*": 6000
  "*": 300
```

Then I ran `s3_website push --force`. But when I check the site through Google Page Speed it still says that I need to enable cache control.

Is there any way to check if cache control has already been enabled on my site? How long does it takes for it to take effect after force push?

**Comment by manabusakai** [comment]
Hi, @iloveip.

Please check the HTTP header (ex. `Cache-Control: max-age=86400`)
It is convenient to Chrome and Firefox developer tools.

**Comment by iloveip** [comment]
Hi @manabusakai,

Thank you very much for your reply. It says Cach-Control is set to `public, max-age=300`. But I keep getting a message in Google Page Speed Insights to enable cache control.

Any ideas how I can fix it?

**Comment by manabusakai** [comment]
That’s all right!

I found this description in the [official reference](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching).

> We recommend a minimum cache time of one week and preferably up to one year for static assets, or assets that change infrequently.

Please extend the period. I think the resolve.

**Comment by iloveip** [comment]
@manabusakai thank you very much!

So one week would be `max-age=604800`?

**Comment by manabusakai** [comment]
> So one week would be max-age=604800?

That's right!

**Comment by iloveip** [comment]
@manabusakai thank you very much! Everything is working now.

**Comment by manabusakai** [comment]
Thats great! :smile:
