### ISSUE TITLE
Provide config file with --config?

### ISSUE THREAD

**Issue by phzbox** [laurilehmijoki/s3_website#221]
Hi, is there a way I can keep my s3_website.yml somewhere else and provide the path from the commandline?

Such as: s3_website cfg apply --config=config/s3_website.yml

Maybe it's already possible but I didn't find it in the config options

**Comment by laurilehmijoki** [comment]
Hi @phzbox , will this help you? https://github.com/laurilehmijoki/s3_website#specifying-the-location-of-your-website

**Comment by phzbox** [comment]
Hi, yes this is perfect, thanks

**Comment by laurilehmijoki** [comment]
np!
