### ISSUE TITLE
error: Java has value '1.8', but '1.6' is required.

### ISSUE THREAD

**Issue by rdyar** [laurilehmijoki/s3_website#224]
I just updated java, and removed old versions. Now S3_website gives an error, Java has value '1.8', but '1.6' is required.

Is 1.6 really required? or maybe it could be updated to allow 1.8?

I am on windows 10.

**Comment by laurilehmijoki** [comment]
Java 1.8 should work. What is the exact error message you are seeing?

**Comment by rdyar** [comment]
never mind - now it works, looks like I needed to reboot. When I upgraded java and tried to use s3_website it said `error: Java has value '1.8', but '1.6' is required`.
