### ISSUE TITLE
push fails in eu-central-1

### ISSUE THREAD

**Issue by raupachz** [laurilehmijoki/s3_website#226]
If your bucket is hosted in Frankfurt (eu-central-1) then the push command fails with the following error message:

**Failed to fetch an object listing (The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: F4EC60DC556F70D1))**

See this [answer on SO](https://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4).

**Comment by laurilehmijoki** [comment]
Unfortunately s3_website does not support eu-central-1.
