### ISSUE TITLE
Support for ap-south-1 AWS region?

### ISSUE THREAD

**Issue by cjshawMIT** [laurilehmijoki/s3_website#227]
The documentation states that you support all S3 region constraints, except for eu-central-1, but I cannot get the new Mumbai (ap-south-1) region to work.

```
[info] Downloading https://github.com/laurilehmijoki/s3_website/releases/download/v2.14.0/s3_website.jar into /home/tomcat/.gem/ruby/gems/s3_website-2.14.0/s3_website-2.14.0.jar
[fail] Could not load the site: Unrecognised endpoint: ap-south-1
```

And my s3_website.yml:

```
s3_endpoint: ap-south-1
```

**Comment by laurilehmijoki** [comment]
The documentation is outdated: Mumbai is not supported either. Care to update the doc?

**Comment by cjshawMIT** [comment]
Are there plans to support it (or alternatively, what would it take to support it)? Is it an issue with signature version (which would also include ap-northeast-2)?

**Comment by laurilehmijoki** [comment]
Some plans are outlined here: https://github.com/laurilehmijoki/s3_website/issues/126

afaik nobody is working on fixing the issue.
