### ISSUE TITLE
Set custom headers

### ISSUE THREAD

**Issue by code-tree** [laurilehmijoki/s3_website#229]
I've got a situation where I have the files I want uploaded gziped already during build, but I assume if I enable gzip in s3_website then they will get double gzipped.

Is it possible to set custom headers for files at upload time? In this case I'd like to set the `content-encoding` header, but it would be nice to set other ones as well.

**Comment by laurilehmijoki** [comment]
When you enable gzip for a file, s3_website sets the S3 content-encoding metadata to `gzip` (https://github.com/laurilehmijoki/s3_website/blob/100e2195f9deefbaf4a8382f63818bfc0f6dcfea/src/main/scala/s3/website/S3.scala#L74).

You are right: if your build tool gzips the file and then you configure s3_website to gzip the same file, then the object on S3 will end up being double gzipped.

Could you elaborate how custom headers would solve this double-gzipped issue?

**Comment by code-tree** [comment]
Sure, instead of enabling gzip in s3_website, I'd set the `content-encoding: gzip` header myself, thereby ensuring browsers unzip the files properly, and avoiding the double zip problem.

I guess I'm thinking of two solutions:
 1. Can s3_website detect if the file is already gzipped, and not zip it again if so?
 2. Have an option to set custom headers and filter by file name
     * Then can set `content-encoding: gzip` only on the zipped files
     * Could also set the caching headers this way too
     * More flexibility for the developer

Do you think either of these solutions could work?

**Comment by laurilehmijoki** [comment]
Regarding your solution 1: sure, upon push we could read each file and see if it contains the gzip magic bytes. There can be some files that are not gzipped but that start with the magic bytes. These files would not get gzipped - for most users this would not be a fatal issue I presume. What so you think about this corner case?

About your solution 2: how would you like to define the custom headers? In the config file, or somewhere else?

**Comment by code-tree** [comment]
If you can implement (1) then that would solve the immediate issue for me. However, if (2) is implemented, then that may not be necessary. I think (2) should probably be the solution, as it would not only solve my gzip issue, but would also allow the developer to customise all headers, opening up many possibilities such as:
 * CORS customisation
 * Amazon x-amz settings
 * (cache control, gzip, reduced redundancy settings could simply be shortcuts for this `meta-data` setting)

I think it is best implemented the same way you've implemented `max-age` and other header-related settings, using the same syntax, so each header can either be:
 1. A literal value (applying to all files)
 2. A mapping of globs and values
    * Except maybe `value: [glob, glob]` rather than `glob: value`?

```
meta-data:
    Access-Control-Allow-Origin: '*'
    Content-Encoding:
        gzip: ['*.txt', '*.html', '*.js']
    x-amz-storage-class:
        REDUCED_REDUNDANCY: ['archives/*']
```

**Comment by code-tree** [comment]
Sorry, nevermind. I was under the impression that you could set any HTTP header in S3 with meta data. I just realised that you can't, and in fact, the options are quite limited.

In that case, maybe option (1) is the best way to go?

**Comment by code-tree** [comment]
So I think the implementation of this would need to be (in pseudo code):

 1. When getting the contentType, if the file is meant to be gzipped, then Tika should be given the filename only so that the mime type is based on the filename (giving the actual file would result in gzip mime type)
 2. Upload function should only create tmp file if Tika says it is not a gzip file (in this case Tika must be passed the whole file)

```
lazy val contentType: Try[String] = tika map { tika =>
    val mimeType = tika.detect(originalFile.filename if gzip else originalFile)
    ...

def uploadFile...
    if gzip and tika(originalFile) != 'application/gzip':
        create tmp file
    else
        use original file
```

**Comment by laurilehmijoki** [comment]
The solution (1) is now released in the version **2.14.1**.

@code-tree please try out the version. It should work – at least according to integration tests. However, I might have missed some corner cases so I could use your help in verifying that the "do not gzip a file if it's already gzipped" feature works like a charm. Thanks!

The commit is here: <https://github.com/laurilehmijoki/s3_website/commit/54f86709574be891e5bbe584e912ddd6d0b36356>.

**Comment by code-tree** [comment]
Thanks Lauri, works well, except Apache Tika is now getting confused, and setting all gzipped files' content type to `application/x-gzip`. I was initially thinking the following might work:

```scala
lazy val contentType: Try[String] = tika map { tika =>
    val mimeType = tika.detect(originalFile)
    // If a gzip file, base mime type on its filename alone (Tika can take file or filename)
    // NOTE: this means actual gzip files should always have a .gz extension
    // It also means files-to-be-gzipped need clear extensions (.txt),
    // however, the gzip setting already expects them to, so probably not an issue.
    if (mimeType == "application/gzip")
        mimeType = tika.detect(originalFile.filename)
```

But I'm now thinking it may be better to replicate what [Nginx gzip_static](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html) does. That is:
 1. Build script can be configured to output files to `filename.gz` rather than `filename`
    * So both original file and gzipped file exist next to each other
 2. If `filename.gz` exists, upload that, otherwise create gzipped tmp file

Or in code form:
```scala
var gzipped_version = originalFile.filename + '.gz'
if (exists(gzipped_version))
    gzipped_version
else
    tmp file
```

s3_website can then be configured to not upload those extra gzip versions via the following:

`exclude_from_upload: '.*\.(?!tar\.)[^\.]+\.gz$'`

**Comment by code-tree** [comment]
Which way do you think would work best?

**Comment by laurilehmijoki** [comment]
I know understand that we need to take into account the "already gzipped" case when setting the mime type. Thanks for bringing up this issue.

I'd like to avoid the `exclude_from_upload` solution you propose because it would require the user to add the setting manually into `s3_website.yml`. I'd like the "support for already gzipped files" feature to work automatically all the way.

What do you think about this:

```scala
  lazy val contentType: Try[String] = tika map { tika =>
    val mimeType = 
      if (fileIsAlreadyGzipped) {
        val unzippedFile = // upzip originalFile into a temp file
        tika.detect(unzippedFile) 
      } else {
        tika.detect(originalFile)
      }
    if (mimeType.startsWith("text/") || mimeType == "application/json")
      mimeType + "; charset=utf-8"
    else
      mimeType
  }
```

The above solution should solve the problem.

If you agree that the above solution is ok, I'll implement it and ship a new version. (Unless you fancy doing it ;))

**Comment by code-tree** [comment]
Your solution sounds good. The only thing I'd add (and you may already mean this) is that `fileIsAlreadyGzipped` should check both:
 1. File is a gzip file
 2. File is matched by the gzip config setting

To ensure that regular gzip files are detected as gzip (and not unzipped).

Thanks Lauri. I'm very new to Scala, so can't trust myself to write the patch myself :)

**Comment by laurilehmijoki** [comment]
Okay, the solution is now released in version **2.14.2**. Please try it out and tell me how it works for you.

The commit is here: https://github.com/laurilehmijoki/s3_website/commit/143396e5e6153344b1d233e76c7ac6cb531e32e4

**Comment by code-tree** [comment]
Fix works great, just one small issue that I've fixed in the pull request.

**Comment by laurilehmijoki** [comment]
Merged and released the pull request. I'm now closing this issue, please re-open if needed.

**Comment by code-tree** [comment]
Works for me, thanks!
