### ISSUE TITLE
Configure mime type based on file extension / change default?

### ISSUE THREAD

**Issue by michaelstepner** [laurilehmijoki/s3_website#232]
Hello,

I've been having an issue with a website I deploy using s3_website. The Stata datasets (with a .dta extension) that I [host on the website](https://healthinequality.org/data/) are automatically given a `text/html` mime type, which causes issues with how browsers and CloudFlare handle the file.  I've temporarily solved the issue by manually changing the .dta files on S3 to the `application/octet-stream` mime type.

Is it possible for me to control which mime type is given to my .dta files when I use `s3_website push`?  In the same spirit as [this StackOverflow answer](http://stackoverflow.com/a/34516715) regarding the vanilla AWS CLI tools?

Alternatively, is there somewhere within s3_website or an upstream gem where we could set a different default for .dta files?

**Comment by laurilehmijoki** [comment]
s3_website uses Apache Tika to determine the content type of each file. It seems that you've run into a bug in Tika. Care to contact the Tika team and report the issue to them?

Upgrading Tika to a newer version might be a good idea. The current version os rather old.

**Comment by michaelstepner** [comment]
Thanks @laurilehmijoki.  I replicated the bug using the latest release of Tika (1.13), which also detects .dta files as `text/html`:

```
$ curl -O http://www.stata-press.com/data/r14/auto.dta
$ java -jar tika-app-1.13.jar --detect auto.dta
text/html
```

As you suggested, I've [reported the bug upstream to Apache Tika](https://issues.apache.org/jira/browse/TIKA-2064).

@laurilehmijoki, do you have any suggestions for a workaround in the meantime?

**Comment by michaelstepner** [comment]
Thanks @laurilehmijoki.  I replicated the bug using the latest release of Tika (1.13), which also detects .dta files as `text/html`:

```
$ curl -O http://www.stata-press.com/data/r14/auto.dta
$ java -jar tika-app-1.13.jar --detect auto.dta
text/html
```

As you suggested, I've [reported the bug upstream to Apache Tika](https://issues.apache.org/jira/browse/TIKA-2064).

@laurilehmijoki, do you have any suggestions for a workaround in the meantime?

**Comment by laurilehmijoki** [comment]
@michaelstepner I just released the version **2.15.0**. Please upgrade into that version and try the following configuration:

```yaml
content_type:
  "*.dta*": application/octet-stream
```

Will that setting solve the problem for you? The implementation of the new `content_type` setting is [here](https://github.com/laurilehmijoki/s3_website/commit/59aaa2d795aed108fa3583fd09c9b1bfec6e8145).

**Comment by laurilehmijoki** [comment]
You need to invoke `s3_website push --force` to override the current content-type values on your S3 bucket.

**Comment by laurilehmijoki** [comment]
Closing as solved. Please reopen if needed.

**Comment by michaelstepner** [comment]
@laurilehmijoki, I disappeared from this thread because I had an injury that interrupted my work. But I wanted write back and thank you for this quick and elegant fix. The new "content_type" config works perfectly.
