### ISSUE TITLE
Add support for enabling/disabling HTTP/2.

### ISSUE THREAD

**Issue by yanokwa** [laurilehmijoki/s3_website#234]
Cloudfront now supports HTTP/2. It'd be great if we can enable/disable this in s3_website. 
https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-cloudfront-now-supports-http2/

**Comment by laurilehmijoki** [comment]
Hi @yanokwa and thanks for bringing up the idea.

Question: can you explain to me why someone would want to disable the HTTP/2 support?

The [documentation](https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-cloudfront-now-supports-http2/) says:

> HTTP/2 is enabled by default for all new Amazon CloudFront distributions, and for existing distributions HTTP/2 can be enabled by editing the distribution configuration.

Obviously, this means that new s3_website-managed CloudFront distributions support HTTP/2 by default.

Current s3_website could benefit from the following new setting

```yaml
# applied when the user calls `s3_website cfg apply` or `s3_website cfg create`
enable_http2_in_cloudfront: true|false 
```

Any thoughts on the above?

**Comment by yanokwa** [comment]
I can't think of a good reason why someone would want to turn off HTTP/2 support, but it's hard to predict how things will fail and being able to toggle protocols seems prudent.

How you've done the settings looks good to me.

**Comment by laurilehmijoki** [comment]
Did you try the following setting?

```yaml
cloudfront_distribution_config:
  http_version: http2
```

I didn't yet have time to verify that the above snippet works, but it should, since `cloudfront_distribution_config` translates into http://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/PutConfig.html

**Comment by yanokwa** [comment]
I have an existing distribution that I manually set to HTTP/2. When I run `s3_website cfg apply` to try to change it to HTTP1.1, the configuration is applied, but I don't see a change in the CloudFront UI.


```
# s3_website.xml
cloudfront_distribution_config:
  http_version: http1.1
  default_cache_behavior:
    min_TTL: <%= 60 * 60 * 24 %>
```

```
# cfg apply results
  Applied custom distribution settings:
    http_version: http1.1
    default_cache_behavior:
      min_TTL: 86400
```

**Comment by laurilehmijoki** [comment]
@yanokwa I don't know why CloudFront refuses to change the HTTP level given the config `http_version: http1.1`. 

I've posted a [question](https://forums.aws.amazon.com/thread.jspa?threadID=239220) on the AWS Developer Forums about this issue.

**Comment by dancoates** [comment]
@laurilehmijoki I think this may be because setting HttpVersion isn't available in the 2012-07-01 version of the AWS Cloudfront API that is used by configure-s3-website. 

I can't see any reference to it in the archived docs: http://awsdocs.s3.amazonaws.com/CF/20120701/cf_api_20120701.pdf

**Comment by laurilehmijoki** [comment]
Once the effort described in https://github.com/laurilehmijoki/configure-s3-website/issues/16#issuecomment-264074020 is completed, this problem should be solved.

**Comment by laurilehmijoki** [comment]
If you upgrade to version **3.0.0**, the setting

```yaml
cloudfront_distribution_config:
  http_version: http2
```

changes the HTTP version to `2`, whereas the setting


```yaml
cloudfront_distribution_config:
  http_version: http1.1
```

will change it back to `1.1`.

Thanks to @dancoates for the idea!
