### ISSUE TITLE
s3_website cfg apply returns certificate error

### ISSUE THREAD

**Issue by jolars** [laurilehmijoki/s3_website#239]
Running `s3_website cfg appl` on my windows machine I get the following error: 
`SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Seahorse::Client::NetworkingError)`

Push works fine, however. I've set up my S3 amazon account according to the documentation.

I'm running Jekyll 3.2.1.

**Comment by laurilehmijoki** [comment]
Does this help you? https://github.com/laurilehmijoki/s3_website/issues/142

**Comment by nanodeath** [comment]
I had the same issue and it helped me.

**Comment by jolars** [comment]
Yes, thanks. It worked for me too, at least downloading the s3_website jar file manually did.
