### ISSUE TITLE
Add command to download s3_website.jar before pushing

### ISSUE THREAD

**Issue by jcbpl** [laurilehmijoki/s3_website#242]
In a CI environment, the s3_website jar file downloaded by the `push` command may not be cached between builds, since `push` will typically be run in a deploy phase that's separate from dependency installation/caching. It'd be nice to be able to include something like `s3_website install` as a dependency command in our CI builds, to force the downloading of the jar file in time for caching.

I'm currently working around this by doing a manual wget (see cityofaustin/austinconventioncenter.com#9), but a built-in command would be a more resilient option.

**Comment by laurilehmijoki** [comment]
Here's the download function: https://github.com/laurilehmijoki/s3_website/blob/master/bin/s3_website#L228

You can write a new [Thor command](http://whatisthor.com/) that invokes that function. Care to submit a pull request on that?
