### ISSUE TITLE
Ignore folder contents on server

### ISSUE THREAD

**Issue by JasonNewton1** [laurilehmijoki/s3_website#247]
Hi there,

I looked through the notes for s3_website.yml and it explains how to ignore files on the server so that they are not deleted.

At the moment, I have this:

ignore_on_server: 
  - styles.css

But I want to also be able to ignore the contents of the images folder (so that they are not deleted every time I push).

How do I add that? Is it like this?

ignore_on_server: 
  - styles.css
  - /images/

Kind Regards

**Comment by laurilehmijoki** [comment]
`ignore_on_server` supports regular expressions, here's an example: https://github.com/laurilehmijoki/s3_website/blob/5a4e9782b1ec787117c7f10b2fc69c5d157f2fa8/src/test/scala/s3/website/S3WebsiteSpec.scala#L607

**Comment by JasonNewton1** [comment]
Thanks, Lauri.

Kind Regards
