### ISSUE TITLE
Support HTTP/2 for Cloudfront

### ISSUE THREAD

**Issue by benarent** [laurilehmijoki/s3_website#259]
Back in September AWS added support for [HTTP/2](https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-cloudfront-now-supports-http2/). 

Since Version 3.0.0 supports the AWS SDK, this shouldn't be too difficult. If I get a chance to poke around, I'll submit a PR.

**Comment by laurilehmijoki** [comment]
Hello, as you said, the HTTP/2 support is already there. An example configuration that sets HTTP version to 2 would be a nice addition. I'm looking forward to your PR.

**Comment by benarent** [comment]
Closing based on merged PR https://github.com/laurilehmijoki/s3_website/pull/260
