### ISSUE TITLE
Use standard AWS SDK/CLI mechanism for credentials

### ISSUE THREAD

**Issue by jeffbyrnes** [laurilehmijoki/s3_website#262]
The [“Configuring the AWS Command Line Interface” docs for the AWS CLI](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) describe the various layers of configuration used for the CLI & the SDKs.

Rather than do an end-run around these, I propose it would be simpler (as it is built-in to the SDKs) t use these.

Specifically, to encourage use of either a credential file (`~/.aws/credentials`) or the environment variables (which override any credentials on disk). This would help avoid someone putting their credentials in a file that is easy to commit and publish by accident.

This even opens up the ability to use named profiles.

**Comment by igilham** [comment]
I agree. Adding credentials to the s3 sync config is not particularly helpful when so many other methods already exist and can be used more safely.

**Comment by laurilehmijoki** [comment]
Good idea! Pull requests appreciated.

**Comment by jeffbyrnes** [comment]
Guess I’ll try & learn some Scala!

**Comment by jeffbyrnes** [comment]
Thank you @pnc and @c0state for making this happen!
