### ISSUE TITLE
please support new subcommand to download jar

### ISSUE THREAD

**Issue by jieryn** [laurilehmijoki/s3_website#268]
It will be useful for Docker containers to be able to have ```RUN s3_website download``` to just download the s3_webiste-x.x.x.jar a single time and not every time we run the s3_website command in a containerized application.

**Comment by laurilehmijoki** [comment]
There already is the `install` command: https://github.com/laurilehmijoki/s3_website/blob/master/bin/s3_website

Will that solve your problem?

**Comment by jessefarinacci** [comment]
Sorry, I did not see that option in my s3_website output.. this works great, thanks!

**Comment by jieryn** [comment]
That works, thanks!
