### ISSUE TITLE
index_document and error_document are not documented

### ISSUE THREAD

**Issue by rayjolt** [laurilehmijoki/s3_website#269]
I see `index_document` and `error_document` in the [configuration file template](https://github.com/laurilehmijoki/s3_website/blob/34f45a4dd5d4a89e74cd418ffd3ca5a2d4232e46/resources/configuration_file_template.yml#L13), but these are not mentioned in README.md, and I do not see them anywhere else in the code. Should these options be removed from the template? (Or have I missed something?)

**Comment by alexey-pelykh** [comment]
Seems that they are just mentioned in that document and not actually supported

**Comment by alexey-pelykh** [comment]
[setBucketWebsiteConfiguration](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#setBucketWebsiteConfiguration-java.lang.String-com.amazonaws.services.s3.model.BucketWebsiteConfiguration-) is not called from anywhere, thus there's no way to configure any of static website settings at this point. That's supported in [npm s3-website](https://github.com/klaemo/s3-website), FYI.

**Comment by laurilehmijoki** [comment]
Index and error docs are mentioned here: https://github.com/laurilehmijoki/configure-s3-website/search?q=index

That's a dependency of this project.
