### ISSUE TITLE
Query about setting max-age and ignoring files

### ISSUE THREAD

**Issue by JasonNewton1** [laurilehmijoki/s3_website#275]
I wanted to quickly ask you question about the S3_website.yml file and it's configuration.
Specifically, which line do I need to alter so that my styles. css file has a very long expiration date?

Whenever I run the .yml file on my s3 bucket, it sets my css to 86400 seconds (one day). This is the default TTL on my distribution (which obviously I do not wish to alter) - I just want to always make sure my css is set far into the future whenever I run s3_website. Is there a way to ignore the CSS object when I push my update?

Can I just do this?

ignore on server:
   - styles.css
   - .*jpg

**Comment by laurilehmijoki** [comment]
Will the following setting solve your problem?

```yaml
cache_control:
  "styles.css": public, max-age=31104000
```

See https://github.com/laurilehmijoki/s3_website#max_age for details.

**Comment by JasonNewton1** [comment]
I'll try this and get back to you. Thanks for replying so quickly, I really appreciate it.

**Comment by JasonNewton1** [comment]
This doesn't seem to make a difference. When I go back into the S3 console and look at the object 'styles.css'), the meta data has been set back to 'Cache-Control max-age=86400'

I've attached my yml file (minus AWS credentials), if it's possible would you be able to take a brief look at it?

Kind Regards

[s3_website.yml.zip](https://github.com/laurilehmijoki/s3_website/files/970268/s3_website.yml.zip)

**Comment by laurilehmijoki** [comment]
Do you have both `max_age` and  `cache_control`? If yes, try removing the `max_age` setting. These two settings are [mutually exclusive](https://github.com/laurilehmijoki/s3_website#cache-control).

**Comment by JasonNewton1** [comment]
Okay, just one moment.

**Comment by JasonNewton1** [comment]
I removed the line:

`"css/*": <%= 60 * 60 * 24 * 365 %>` but it hasn't made a difference. The css file still has the same value of 86400.

Kind Regards

**Comment by laurilehmijoki** [comment]
Try removing the `"*": <%= 60 * 60 * 24 %>` setting in your `max_age` config.

**Comment by JasonNewton1** [comment]
I removed that line but my CSS file still has 'Cache-Control max-age=86400' on the S3 console.

**Comment by laurilehmijoki** [comment]
Do you still have that `ignore_on_server` setting?

**Comment by JasonNewton1** [comment]
yes, I do.

**Comment by JasonNewton1** [comment]
I also have this now:

``max_age:``
 `` "css/*": <%= 60 * 60 * 24 * 365 %>``
  ``"fonts/*": <%= 60 * 60 * 24 * 365 %>``
 `` "images/*": <%= 60 * 60 * 24 * 365 %>``

**Comment by JasonNewton1** [comment]
I removed the ``ignore_on_server`` and it seems to have fixed it.
Thanks again.

**Comment by laurilehmijoki** [comment]
:thumbsup:
