### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by yanokwa** [laurilehmijoki/s3_website#330]
A big thank you to @laurilehmijoki for all the work he's put into s3_website. It's always been a joy to use and I'm sad that he no longer has the time to maintain it. 

Lauri has graciously given the community [permission to fork](https://github.com/laurilehmijoki/s3_website/commit/edc97d1974c450dbc0cec54cecd2613940cd386e#commitcomment-34652974) and it looks like there is [some interest](https://github.com/laurilehmijoki/s3_website/pull/329#issuecomment-528587286).

I don't have the right skillset to lead a fork, so I'm filing this ticket in hopes that others with Scala and Ruby experience will step forward to lead.

If you are interested in leading a fork of s3_website, please write a comment below describing your relevant experience. And if you see a comment from a person who you think should lead the fork, vote with a thumbs up.

**Comment by nabilfreeman** [comment]
Just wondering if there's any update on the maintenance situation?

I'm very keen to keep this library alive but have recently thinking it might be better to transfer it into a more maintainable technology like Node.js.

I recently did a lot of work with the AWS SDK for another deployment script and have a pretty good understanding of how it works, and I think it's totally possible to migrate this and keep everybody's config files compatible etc.

The ideal solution would be for people to do

```
npm install s3-website
```

in their existing projects, uninstall the Ruby gem and then `s3_website` would be a JS script that is feature complete, minus all the random crashes and bugs.

In our Jekyll workspace we are already doing a huge amount of Node operations for fetch, preformatting content etc and it works well for us.

Thoughts appreciated.

**Comment by yanokwa** [comment]
@nabilfreeman No change on maintenance front. If your proposal is to create a Node.js version, there's nothing preventing you from doing that and making it compatible with s3_website's config. I'd certainly encourage you to give it a go if you are interested, but out of respect to Lauri, it seems like it should be called something besides s3_website.

**Comment by theonlyguills** [comment]
@nabilfreeman Coming from a large enterprise / government background, "let's rewrite it in another language" projects are pitched weekly are not usually the most successful. There is a lot that goes into a project like this. What is more maintainable about Node?

On the maintenance front I really wish to keep this project alive as I use it but I don't have much time either. How about for starters we can fork it somewhere else so at least we have a viable fork with issue tracking and releases. I volunteer my fork if you want over at [https://github.com/cloudvolution/s3_website](https://github.com/cloudvolution/s3_website). I can try to merge pull requests but I don't think I'll have much time to dig into code myself for now, it might get easier when this covid situation changes. Also if we could manage to get a hold of the original admin of the gem I could try to get access to update it with @yanokwa's latest.

At any point if anyone wants to hop in and lead this the fork can stay there and I can just hand over all the access.

**Comment by nabilfreeman** [comment]
Hey @yanokwa, I think that's very fair. I won't be pursuing that direction anyway as we have abandoned Jekyll and are in the the process of subbing it out for Hugo.

The syntax isn't quite as nice but it handles front matter much better than Jekyll and critically renders on multiple threads which allows to build our 15k page site in seconds on a 64 core CI!

Will look back fondly on this library but to also excited to not be debugging Scala any more 😅

Thanks and all the best

**Comment by jtoy** [comment]
please someone fix it, its broken and is still recommended option for jekyll and s3.

**Comment by ivoanjo** [comment]
For what it's worth, I'm using it successfully on Ruby 3.1 + JVM 8. I had to do some minimal changes in my fork ( https://github.com/ivoanjo/s3_website ) but happy camper.

**Comment by ivoanjo** [comment]
Update: I've renamed my fork to https://github.com/ivoanjo/s3_website_revived and published it on rubygems https://rubygems.org/gems/s3_website_revived . Hope it's useful for someone out there.

**Comment by yanokwa** [comment]
Closing because https://github.com/laurilehmijoki/s3_website/pull/336 adds a link to s3_website_revived. Long live s3_website 😀
