### ISSUE TITLE
unsupported Java version: 17

### ISSUE THREAD

**Issue by ndvbd** [laurilehmijoki/s3_website#335]
unsupported Java version: 17

Any ideas?

**Comment by ivoanjo** [comment]
You can use my fork instead, it should work on Java 17: https://github.com/ivoanjo/s3_website

**Comment by ndvbd** [comment]
@ivoanjo How can we install your fork? Can you add to your documentation?

**Comment by ivoanjo** [comment]
@ndvbd you can install it [directly from git](https://bundler.io/guides/git.html):

```ruby
gem 's3_website', git: 'https://github.com/ivoanjo/s3_website.git'
```

If there's interest, I can try pushing a release on rubygems.org, but I wasn't sure if anyone else still wanted it, so I got slightly lazy ;)

**Comment by stmgit** [comment]
I tried installing your fork as listed above but get this error.
`gem 's3_website', git: 'https://github.com/ivoanjo/s3_website.git'
ERROR:  While executing gem ... (Gem::UnknownCommandError)
    Unknown command s3_website,
`
I'm using the latest bundler: `Successfully installed bundler-2.4.7`
I'm hoping to get this working on Ubuntu 22.04 or I'll have to give up on s3_website and look for alternatives.
Thanks for your help.

**Comment by ivoanjo** [comment]
@stmgit The instructions above are for installing the gem using bundler -- you need to add that incantation to your `Gemfile` or `gems.rb` file and then run `bundle install` (I've also updated the comment above to make that more clear).

Let me know if that doesn't work for you! Installing using `gem` directly on the command-line is a bit more awkward, but I can also share the instructions for doing that :)
