### ISSUE TITLE
Setting up API credentials

### ISSUE THREAD

**Issue by dominikwilkowski** [laurilehmijoki/s3_website#41]
Hi there,

I am sure this is something easy that I just can't see right now but I seem to be unable to set up the correct API credentials.

What I got so far:
I added a user in IAM with the group policy and user policy as follows:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": "*"
    }
  ]
}
```

And still get `AllAccessDisabled` when I do `s3_website cfg apply`.

The very same credentials work fine when using an FTP client like `Transmit`. Are there any other settings I'm not aware of that have to be set for this to work?

Any help is appreciated.

**Comment by siruguri** [comment]
The solution suggested by @dominikwilkowski didn't work for me ... It didn't matter, `s3_website push` still works, and I configured my bucket on the AWS console anyway. But `cfg apply` still fails with just an `AccessDenied` message, even when my `s3_bucket` setting has `domain.com` appended to the bucket name.
