### ISSUE TITLE
Octopress uses 'public' default output directory, s3_website expects Jekyll's _site

### ISSUE THREAD

**Issue by alexandroid** [laurilehmijoki/s3_website#48]
It would be nice to override default site root in `s3_website.yml` so one does not have to invoke `s3_website push --site public`.

Alternatively, `s3_website` can fallback to `public` if `_site` does not exist. Since it's positioned to work with Octopress it looks weird that it does not find `public` by default... am I missing something?

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.
