### ISSUE TITLE
Route 53 Auto-config

### ISSUE THREAD

**Issue by rsprabery** [laurilehmijoki/s3_website#50]
Hi, this gem is really helpful and has really helped me cut down on time to deploy to s3.

I had an idea regarding adding an option for Route 53 in the config file that would auto configure your dns were you using Route 53 (which I suspect most people doing this are).

I could use the [ruby_route_53](https://github.com/pcorliss/ruby_route_53) library for implementation.

### Notes ###
+ Disabled by default (commented out sections in `s3_website.yml` much like the gzip options)
+ Option to create additional buckets that point to the `s3_bucket` specified in the config.
 + Ex: `s3_bucket: www.example.com` with an option that would create a bucket for `example.com` set to redirect
+ Will run with `s3_website apply cfg` with error messages for:
 + Optional bucket already exists
 + DNS not on route53 (won't create a new hosted zone if not already on there)
 + Ask the user (with another `[Y/n]`) if they want to override an existing dns entry if one exists for either the optional buckets (those that redirect) and the main bucket.

Let me know what you think and I can get started on it.  The only problem that I can see with it is that it does add another dependency.

**Comment by natarajs** [comment]
Hi,
       Route53 and S3 support assigning multiple domains to the same bucket. This in many cases is better than redirects. For example, we could support www.mydomain.com and www.mydomain.org from same S3 Bucket. Would it be possible to support this? Perhaps it is supported already, but I am not sure how to set this up. 

       I can open up a new issue if that is a better way to request this.

**Comment by laurilehmijoki** [comment]
s3_website does not currently provide tooling for Route53. I'm not sure if it even should. 

How would you like to express your DNS settings in the *s3_website.yml* file?

**Comment by rsprabery** [comment]
Having worked on this, I agree with @laurilehmijoki - there are simply too many edge cases with Route53 (particularly when considering point it to Amazon's CDN) for it to be included in this project.

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.
