### ISSUE TITLE
Define "Sufficient Permissions" for IAM users

### ISSUE THREAD

**Issue by vijedi** [laurilehmijoki/s3_website#57]
The documentation for IAM users states "create API credentials that have sufficient permissions." The documentation does not list what specific permissions are required on a bucket to use the gem.

**Comment by rileylark** [comment]
I'd like to see an actual list of required permissions - there are some permissions granted by `"*"` that I don't want to pass out

**Comment by Hesesses** [comment]
+1

I would only want to see required permissions, not *
