### ISSUE TITLE
Automatically set files to public once uploaded

### ISSUE THREAD

**Issue by mattlanham** [laurilehmijoki/s3_website#73]
Hi There,

I may be doing something wrong, but each time i push the website up to S3 i have to manually set all of the files and folders to public again to get around the 403 access denied, would it be possible to automate this, or is there something else i can do?

**Comment by guaka** [comment]
S3 noob experiencing the same problem.
What do I do with the policy indicated above?

**Comment by laurilehmijoki** [comment]
Go to [AWS Console](https://console.aws.amazon.com) and open the bucket policy editor of your S3 website bucket. Add the indicated policy there. Does that solve your problem?

**Comment by eremzeit** [comment]
I had the same problem, but the policy above didn't work.  I had better luck with the following policy. 

```
  "Version":"2012-10-17",
  "Statement":[{
	"Sid":"PublicReadGetObject",
        "Effect":"Allow",
	  "Principal": "*",
      "Action":["s3:GetObject"],
      "Resource":["arn:aws:s3:::example-bucket/*"
      ]
    }
  ]
}
```

Source: http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteAccessPermissionsReqd.html

**Comment by rossdakin** [comment]
For those Googling, @eremzeit's solution worked for me.

**Comment by robouk** [comment]
+1 @eremzeit solution

**Comment by chenware** [comment]
I was kind of baffled by not having more information about setting bucket permissions – it was clear that I was making the site private after each build but I couldn't understand why s3_website was doing that. Would liked to have seen some documentation around this.

That said, @eremzeit 's solution seems to have fixed the issue, though. Using this in a middleman + DatoCMS + CircleCI + S3 + Cloudfront site.

**Comment by DuzAwe** [comment]
Same boat here, Every push makes it 403. @eremzeit solution works for me

**Comment by tfnaylor** [comment]
At the risk of being Captain Obvious here, it might be useful to point out that if you let S3_website create your S3 bucket for the first time you will not have this problem since the policy will be set for you. If (like me), on the other hand, you already created your S3 bucket and THEN let S3_website deploy to it, you will need to go back and set the policy manually. At least this is my experience.
