### ISSUE TITLE
-bash: s3_website: command not found 

### ISSUE THREAD

**Issue by bfoste01** [laurilehmijoki/s3_website#92]
Admittedly new at static website development... at the deployment stage, and want to use s3_website to send my Jekyll blog to S3.

**The Issue:**
s3_website cfg create
-bash: s3website: command not found

s3_website shows up in my gem env
**\* LOCAL GEMS ***

aws-sdk (1.40.3)
colored (1.2)
configure-s3-website (1.5.5)
deep_merge (1.0.0)
erubis (2.7.0)
filey-diff (2.0.0)
json (1.8.1)
mime-types (1.25.1)
mini_portile (0.6.0)
nokogiri (1.6.2.1)
s3_website (1.7.6)
simple-cloudfront-invalidator (1.0.1)
thor (0.18.1)
zopfli (0.0.3)

What's the deal?

Thanks in advance. Apologies if this ends up being a basic fix, I have been at trying to figure this out for a while, so this isn't an impulse post. 

Thanks,
B

**Comment by Stephanyan** [comment]
@bfoste01 I've got the same issue but I don't understand what you have done to fix this problem.
Like you bash (zsh for me) does not know s3_website command while I have run the gem.
What do you by "add the GEM EXECUTABLE directory to PATH"?
I also want to host my Jekyll project to by the way. Thank you!

**Comment by bryanus** [comment]
Had the same issue. I was using rbenv to manage my Gems and after installing s3_website I forgot to run:

`rbenv rehash`

**Comment by bobbyarcher** [comment]
> Fixed.
> 
> Needed to add the GEM EXECUTABLE directory to PATH.
> 
> Sorry to clutter the comments.

Can you explain what you meant by this and how you fixed it please?
