### ISSUE TITLE
Smarter Redirects

### ISSUE THREAD

**Issue by pathawks** [laurilehmijoki/s3_website#96]
It would be really awesome if **s3_website** could work with plugins like **[Jekyll's RedirectFrom](https://github.com/jekyll/jekyll-redirect-from)** to make proper redirects on S3.

**RedirectFrom** allows multiple URLs to be listed in a post's front-matter that are then turned into redirects to that posts canonical URL. It does this by creating simple HTML files at the redirect location that contain redirect information in the HTML head.

```html
<!DOCTYPE html>
<meta charset=utf-8>
<title>Redirecting...</title>
<link rel=canonical href="#{item_url}">
<meta http-equiv=refresh content="0; url=#{item_url}">
<h1>Redirecting...</h1>
<a href="#{item_url}">Click here if you are not redirected.</a>
<script>location='#{item_url}'</script>
```

Right now, **s3_website** only creates redirects from a list of URLs in the config file. I'm not sure there is a good way for a Jekyll plugin to modify this config file without risking Very Bad Things.

Instead, perhaps **s3_website** could scan HTML files for the `http-equiv=refresh` line, and use that information to create a proper S3 redirect? Is there a better way to add support for something like this?

**Comment by laurilehmijoki** [comment]
Closing as inactive. Please reopen if needed.
